### ISSUE TITLE
DIND Question

### ISSUE THREAD

**Issue by spohnan** [mesosphere/mesos-slave-dind#9]
Just a question, given the following article listing the possible problems associated with DIND for CI do you think it would be a better approach to use build worker containers with the container host Docker socket volume mounted?

https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

Example plugin config using jpetazzo suggestion
https://github.com/spohnan/jenkins-mesos/blob/master/conf/config.xml#L48

**Comment by ghost** [comment]
This repo is for running a _Mesos_ slave within a Docker container and isn't related to Jenkins build slaves. If you wouldn't mind creating an issue over at https://github.com/mesosphere/jenkins-dind-agent, I'd be happy to go over the design decisions of using Docker-in-Docker.
